### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by buzz-js** [buzz-js/lsdb#1]
Improve documentation, specify requireor parameters and options as well as type

You can use: 

- [JSDoc](https://jsdoc.app/)

**Comment by SMAKSS** [comment]
@buzz-js Well, I would like to claim this one. 😁

**Comment by buzz-js** [comment]
> @buzz-js Well, I would like to claim this one. 😁

Of course all yours 😎

**Comment by SMAKSS** [comment]
Is it just [this](https://github.com/buzz-js/lsdb/blob/master/lib/lsdb.js) single file?

**Comment by buzz-js** [comment]
> > Is it just [this](https://github.com/buzz-js/lsdb/blob/master/lib/lsdb.js) single file?
> 
> Yes, it is a single file

The path has changed now it is in `src`

**Comment by SMAKSS** [comment]
> > > Is it just [this](https://github.com/buzz-js/lsdb/blob/master/lib/lsdb.js) single file?
> > 
> > 
> > Yes, it is a single file
> 
> The path has changed now it is in `src`

Well, the file is now changed to `.ts` are you sure it still needs a JSDOC?

**Comment by buzz-js** [comment]
> > > > Is it just [this](https://github.com/buzz-js/lsdb/blob/master/lib/lsdb.js) single file?
> > > 
> > > 
> > > Yes, it is a single file
> > 
> > 
> > The path has changed now it is in `src`
> 
> Well, the file is now changed to `.ts` are you sure it still needs a JSDOC?

Yeah.

[https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)
