### ISSUE TITLE
Filter results by query

### ISSUE THREAD

**Issue by buzz-js** [buzz-js/lsdb#2]
Implement `where` queries based on subset of mongo query syntax, it handles for example: 

$eq, $ne, $gt, $gte, $lt, $lte, $in

**Comment by fr0stylo** [comment]
Could you tell more more what you expect ?

**Comment by buzz-js** [comment]
> Could you tell more more what you expect ? Maybe some kind of example usage ? Or it is as straight forward as add not existent operators ?

Here are some examples of what I want to achieve

```
const lsdb = new Lsdb("lsdb");
lsdb.collection(["categories", "articles"]);

// implicit (assumes $eq operator)
const articles =lsdb.find('articles', { where: {  title: 'Home'  } })

// explicit $eq
const articles = lsdb.find('articles', { where: { title: { $eq: 'Home' } } })

// $gt
const articles =  lsdb.find('articles', { where: {  age: { $gt: 18  } } })

// $in
const articles = lsdb.find('articles', { where: { name: { $in: ['odin', 'thor'] } } })
```

**Comment by fr0stylo** [comment]
Thank you. Could You assign it to me ?

**Comment by buzz-js** [comment]
> Thank you. Could You assign it to me ?

Enjoy ;)

**Comment by fr0stylo** [comment]
Pull request: https://github.com/buzz-js/lsdb/pull/7

**Comment by fr0stylo** [comment]
Updated version of $in query https://github.com/buzz-js/lsdb/pull/22
It should find in array or non-array objects values.

**Comment by buzz-js** [comment]
@fr0stylo Important contribution, thanks 🎉
