### ISSUE TITLE
Create a Logo/Icon/Favicon

### ISSUE THREAD

**Issue by buzz-js** [buzz-js/lsdb#20]

**Comment by Awsomebuddy** [comment]
can i work on this ?

**Comment by buzz-js** [comment]
Hey, sure! 🌈

**Comment by rachitmanas** [comment]
Hi @buzz-js . How is this logo supposed to look like?

**Comment by buzz-js** [comment]
> Hi @buzz-js . How is this logo supposed to look like?

I haven't thought of something specific, what do you think?
